language: node_js
env:
  - CXX=g++-4.9
sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - librsvg2-dev
      - g++-4.9
cache:
  apt: true
script:
  - yarn test
