language: node_js
env:
  - CXX=g++-5
sudo: required
before_install:
  - npm install -g node-gyp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
script:
  - yarn test --coverage
