import {ColorProperty} from "src/property/ColorProperty";
import {NumberProperty} from "src/property/NumberProperty";
import {Property} from "src/property/Property";

export interface IStyleAttributes {
  alignmentBaseline: Property;
  baselineShift: Property;
  clip: Property;
  clipPath: Property;
  clipRule: Property;
  color: ColorProperty;
  colorInterpolation: Property;
  colorInterpolationFilters: Property;
  colorProfile: Property;
  colorRendering: Property;
  cursor: Property;
  direction: Property;
  display: Property;
  dominantBaseline: Property;
  enableBackground: Property;
  fill: Property;
  fillOpacity: NumberProperty;
  fillRule: Property;
  filter: Property;
  floodColor: Property;
  floodOpacity: Property;
  fontFamily: Property;
  fontSize: Property;
  fontSizeAdjust: Property;
  fontStretch: Property;
  fontStyle: Property;
  fontVariant: Property;
  fontWeight: Property;
  glyphOrientationHorizontal: Property;
  glyphOrientationVertical: Property;
  imageRendering: Property;
  kerning: Property;
  letterSpacing: Property;
  lightingColor: Property;
  markerEnd: Property;
  markerMid: Property;
  markerStart: Property;
  mask: Property;
  opacity: Property;
  overflow: Property;
  pointerEvents: Property;
  shapeRendering: Property;
  stopColor: Property;
  stopOpacity: Property;
  stroke: ColorProperty;
  strokeDasharray: Property;
  strokeDashoffset: Property;
  strokeLinecap: Property;
  strokeLinejoin: Property;
  strokeMiterlimit: Property;
  strokeOpacity: Property;
  strokeWidth: Property;
  textAnchor: Property;
  transform: Property;
  textDecoration: Property;
  textRendering: Property;
  unicodeBidi: Property;
  vectorEffect: Property;
  visibility: Property;
  wordSpacing: Property;
  writingMode: Property;
}
